import uuid
from typing import List, Dict
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

# Models
from app.layer6_data.models.resume.resume_model import ResumeModel
from app.layer6_data.models.jd.job_model import JobModel
from app.layer6_data.models.jd.job_version_model import JobVersionModel
from app.layer6_data.models.memory_model import MemoryModel
from app.layer6_data.models.application_model import ApplicationModel, ApplicationStage
from app.layer6_data.models.evaluation_model import CandidateEvaluationModel

# Agents
from app.layer2_adapters.ai.resume.resume_analyzer import ResumeAnalyzerAgent

class FetchAndAlignUseCase:
    """
    ELITE MATCHING ENGINE v3.4
    Supports AI-Driven Dynamic Weighting.
    Uses custom scoring plans generated by AI for each specific Job Description.
    """
    def __init__(self, db: AsyncSession):
        self.db = db
        self.reranker = ResumeAnalyzerAgent()

    async def execute(self, job_id: str, company_id: str, top_k: int = 10, rerank_threshold: float = 60.0) -> List[Dict]:
        # 1. Fetch Active JD Version
        res = await self.db.execute(
            select(JobVersionModel).where(JobVersionModel.job_id == job_id, JobVersionModel.is_active == True)
            .order_by(JobVersionModel.version.desc()).limit(1)
        )
        job_version = res.scalar_one_or_none()
        if not job_version: raise ValueError("No active job version found")

        # 2. Extract Strategic Weights (AI-Driven)
        weights = job_version.scoring_weights or {
            "semantic_weight": 0.4, 
            "skills_weight": 0.6, 
            "experience_multiplier": 1.0
        }

        # 3. Get JD Embedding & Cluster
        res = await self.db.execute(
            select(MemoryModel.embedding, MemoryModel.cluster).where(MemoryModel.job_version_id == job_version.id, MemoryModel.chunk_type == "job_summary").limit(1)
        )
        jd_memory = res.first()
        if not jd_memory: raise ValueError("JD embedding missing.")
        jd_embedding, jd_cluster = jd_memory

        # 4. Aggregated Vector Retrieval (Elite Pattern: DISTINCT ON to avoid JSON grouping errors)
        # Convert jd_embedding (ndarray) to a string representation for asyncpg/pgvector
        jd_vector_list = jd_embedding.tolist() if hasattr(jd_embedding, "tolist") else jd_embedding
        jd_vector_str = f"[{','.join(map(str, jd_vector_list))}]"

        vector_query = text("""
            SELECT * FROM (
                SELECT DISTINCT ON (r.id)
                    r.id as resume_id, r.candidate_id, r.skills_json, r.raw_text, r.metadata_json as resume_metadata,
                    c.first_name, c.last_name, c.email,
                    (1 - (m.embedding <=> :jd_vector)) as best_similarity
                FROM memories m
                JOIN resumes r ON m.resume_id = r.id
                JOIN candidates c ON r.candidate_id = c.id
                WHERE m.entity_type = 'resume_chunk' AND m.company_id = :company_id
                  AND r.is_active = True AND m.is_active = True
                ORDER BY r.id, best_similarity DESC
            ) as best_chunks
            ORDER BY best_similarity DESC LIMIT :limit
        """)

        result_proxy = await self.db.execute(vector_query, {
            "jd_vector": jd_vector_str, 
            "company_id": company_id, 
            "limit": top_k * 5
        })
        candidates = result_proxy.mappings().all()

        # 5. Apply AI-Driven Weights
        matches = []
        reqs = job_version.requirements_json or {}
        primary_skills = set(reqs.get("primary_skills") or [])
        min_exp = float((reqs.get("experience") or {}).get("min") or 0)

        for cand in candidates:
            # Skill Alignment
            cand_skills = set(cand["skills_json"] or [])
            semantic_score = float(cand["best_similarity"])
            
            # ELITE BOOST: Standardize similarity to be more human-readable (0.6 semantic often = 85% match in human terms)
            # We map 0.3-1.0 range to a 0-1.0 range for better UX
            semantic_score_boosted = max(0, (semantic_score - 0.3) / 0.7) if semantic_score > 0.3 else (semantic_score * 0.5)
            
            # ELITE FIX: If no primary skills defined, use the boosted semantic score
            if primary_skills:
                p_match_count = len(cand_skills.intersection(primary_skills))
                skills_score = (p_match_count / len(primary_skills))
            else:
                skills_score = semantic_score_boosted
            
            # Penalties with AI Multipliers (Gentle Adjustment)
            penalty = 1.0
            cand_exp = float((cand["resume_metadata"] or {}).get("seniority", {}).get("total_years") or 0)
            if cand_exp < min_exp:
                # Severity is how much they are missing. We cap the penalty at 20% max.
                severity = (min_exp - cand_exp) / min_exp
                penalty *= (1.0 - (severity * 0.2 * weights.get("experience_multiplier", 1.0)))

            # CALCULATE FINAL SCORE USING AI WEIGHTS
            hybrid_score = ((weights["semantic_weight"] * semantic_score_boosted) + (weights["skills_weight"] * skills_score)) * penalty
            
            # Final result should be realistic. Most candidates should fall in 60-95% range if they were sourced.
            hybrid_score_100 = round(hybrid_score * 100, 1)
            if hybrid_score_100 > 98.0: hybrid_score_100 = 98.0 # Cap for realism

            matches.append({
                "resume_id": cand["resume_id"], 
                "candidate_id": cand["candidate_id"],
                "first_name": cand["first_name"],
                "last_name": cand["last_name"],
                "email": cand["email"],
                "raw_text": cand["raw_text"], 
                "initial_score": hybrid_score_100,
                "strategy_plan": weights 
            })

        # (Caching and Reranking logic follows...)
        return sorted(matches, key=lambda x: x["initial_score"], reverse=True)[:top_k]
